name: suitmedia_01
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  easy_debounce: ^2.0.3
  logger: ^2.2.0
  sizer: ^2.0.15
  skeletonizer: ^1.3.0
  iconsax_plus: ^1.0.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.6.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.2.0
  fpdart: ^1.1.1
  pretty_dio_logger: ^1.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  riverpod_lint: ^2.1.1
  flutter_gen_runner: ^5.10.0
  json_serializable: ^6.9.5
  freezed: ^3.1.0
  riverpod_generator: ^2.3.3


flutter:

  uses-material-design: true